var cnvs=document.createElement("canvas"),ctx=cnvs.getContext("2d"),canvas_vector=new Vector(200,200),map=[],temp_map=[],outline=[],map_h,map_w,BOX_D=30,draw_map=!1,spawn_v=new Vector(0,0),w=1500,h=700,offset=new Vector(0,0),prev_offset=new Vector(0,0),draw_window=new Vector(0,0),draw_end=new Vector(0,0),draw_x=0,draw_y=0,cast_range;cnvs.width=w;cnvs.height=h;document.body.appendChild(cnvs);var PI=Math.PI,_45=0.75*PI,_90=0.5*PI,_135=0.25*PI,_180=PI,_270=1.5*PI,_360=2*PI;
$(".toast").bind({mouseenter:function(){$(".toast").addClass("shadow")},mouseleave:function(){$(".toast").removeClass("shadow")}});function Vector(a,b){a instanceof Vector?this.copy(a):(this.x=a||0,this.y=b||0)}Vector.prototype.offset=function(a,b){this.x+=a;this.y+=b};Vector.prototype.set=function(a,b){this.x=a;this.y=b};Vector.prototype.addV=function(a){this.x+=a.x;this.y+=a.y};Vector.prototype.subV=function(a){this.x-=a.x;this.y-=a.y};Vector.prototype.copy=function(a){this.x=a.x;this.y=a.y};
Vector.prototype.distanceTo=function(a){return Math.sqrt(Math.pow(a.x-this.x,2)+Math.pow(a.y-this.y,2))};Vector.prototype.equals=function(a){return this.x==a.x&&this.y==a.y};function getAngle(a,b){var d,e=a.x-b.x,f=a.y-b.y;0!==e?(d=toDegrees(Math.atan(f/e)),0<e&&0<f?d+=180:0>e&&0<f?d+=360:0>e&&0>f||(d=0<e&&0>f?d+180:0<e?180:0)):d=0<f?270:90;return d}function getCords(a,b,d){var e=a.getBoundingClientRect();return new Vector(b-e.left*(a.width/e.width),d-e.top*(a.height/e.height))}
function toRadians(a){return a*(PI/180)}function toDegrees(a){return a*(180/PI)}function getQuad(a,b){b&&(a=toDegrees(a));return 0<a&&90>a?1:90<a&&180>a?2:180<a&&270>a?3:270<a&&360>a?4:5}function toggleMap(){draw_map=!draw_map;document.body.style.background=draw_map?"blue":"black"}
function handelDeath(a){a?player.respawn()?(game=player.draw=!0,player.color="yellow"):init():(ctx.clearRect(0,0,w,h),document.getElementById("introToast").className="toast");document.getElementById("deadToast").className="invis"}function handelNextLvl(a){a&&init();document.getElementById("nextLvlToast").className="invis"}function getRandomInt(a,b){return Math.floor(Math.random()*(b-a+1))+a}
function addShadow(a){a.className.match(/(?:^|\s)shadow(?!\S)/)?a.className=a.className.replace(/(?:^|\s)shadow(?!\S)/g,""):a.className+=" shadow "}function toggleAudio(){(sound=!sound)?background_audio.play():background_audio.pause()}var size_x=60,size_y=40,fillprob=40,gens=2,params={r1_cutoff:5,r2_cutoff:1,reps:2},TILE_WALL=1,TILE_FLOOR=0,map1=[];function Box(a,b,d,e){this.pos=a;this.w=b;this.l=d;this.solid=e||!1}
Box.prototype.draw=function(a){ctx.strokeStyle=a||"black";ctx.strokeRect(this.pos.x,this.pos.y,this.w,this.l);this.solid&&(ctx.fillStyle=a||"black",ctx.fillRect(this.pos.x,this.pos.y,this.w,this.l))};Box.prototype.checkCollision=function(a){if(!this.solid)return!1;var b=this.pos.y+this.l;return this.pos.x+this.w>=a.x&&a.x>=this.pos.x&&b>=a.y&&a.y>=this.pos.y?!0:!1};Box.prototype.set=function(a,b,d,e){this.pos=new Vector(a,b);this.l=this.w=d;this.solid=e};
function randpick(){return getRandomInt(1,100)%100<fillprob?TILE_WALL:TILE_FLOOR}function initMap(){var a,b;for(b=0;b<size_y;b++)for(map[b]=[],map1[b]=[],a=0;a<size_x;a++)map[b].push(randpick()),map1[b].push(TILE_WALL);for(b=0;b<size_y;b++)map[b][0]=map[b][size_x-1]=TILE_WALL;for(a=0;a<size_x;a++)map[0][a]=map[size_y-1][a]=TILE_WALL}
function generateMap(){var a,b,d,e;for(b=1;b<size_y-1;b++)for(a=1;a<size_x-1;a++){var f=0,g=0;for(d=-1;1>=d;d++)for(e=-1;1>=e;e++)map[b+d][a+e]!=TILE_FLOOR&&f++;for(d=b-2;d<b+2;d++)for(e=a-2;e<a+2;e++)if(2!=Math.abs(d-b)||2!=Math.abs(e-a))0>d||0>e||d>=size_y||e>=size_x||map[d][e]!=TILE_FLOOR&&g++;map1[b][a]=f>=params.r1_cutoff||g<=params.r2_cutoff?TILE_WALL:TILE_FLOOR}for(b=1;b<size_y-1;b++)for(a=1;a<size_x-1;a++)map[b][a]=map1[b][a]}
function cleanMap(){for(var a,b=1;b<size_y-1;b++)for(a=1;a<size_x-1;a++){var d=0,e=0;for(n=-1;1>=n;n++)for(k=-1;1>=k;k++)map[b+n][a+k]!=TILE_FLOOR&&d++;for(n=b-2;n<b+2;n++)for(k=a-2;k<a-2;k++)if(2!=Math.abs(n-b)||2!=Math.abs(k-a))0>n||0>k||n>=size_y||k>=size_x||map[n][k]!=TILE_FLOOR&&e++;map1[b][a]=d>=params.r1_cutoff||e<=params.r2_cutoff?TILE_WALL:TILE_FLOOR}}
function drawMap(a){var b=new Box(new Vector(0,0),10,10,0),d,e;ctx.strokeStyle="black";for(d=size_y-1;0<=d;d--)for(e=size_x-1;0<=e;e--)b.set(e*a,d*a,a,map[d][e]),b.draw()}function createMap(a){initMap();for(var b=0;b<gens;b++)for(var d=0;d<params.reps;d++)generateMap(),cleanMap();drawMap(a);map_w=size_x*BOX_D;map_h=size_y*BOX_D}
function checkMap(a){var b=new Vector(a.x,a.y),d=new Vector(a.x,a.y),e=[],f=[],g,l,m=0;e.push(new Vector(d.x,d.y));do{if(m>size_x*size_y)return!1;d.copy(b);g=getRandomInt(-1,1);l=getRandomInt(-1,1);d.offset(g,l);if(vectorIn(e,d)&&!d.equals(a)){if(vectorIn(f,d)||f.push(new Vector(d.x,d.y)),8==f.length){if(b.equals(a))return!1;b.copy(a);f.length=0}}else{if(map[d.y][d.x]==TILE_WALL){if(vectorIn(f,d)||f.push(new Vector(d.x,d.y)),8==f.length){if(b.equals(a))return!1;b.copy(a);f.length=0}}else if(b.copy(d),
e.push(new Vector(d.x,d.y)),f.length=0,50<e.length)return!0;m++}}while(1)}function vectorIn(a,b){if(0===a.length)return!1;for(var d=a.length-1;0<=d;d--)if(a[d].equals(b))return!0;return!1}var abox=new Box(new Vector(0,0),10,10,0);function Ray(a,b,d){this.pos=a;this.a_r=b;this.far=d;this.end=this.calcEnd();this.collision=!1}var vector=new Vector(0,0);Ray.prototype.cast=function(){var a=0;do{if(this.testAngle(a))return!0;a++}while(a<this.far);return!1};
Ray.prototype.testAngle=function(a){var b,d;_90<this.a_r&&this.a_r<_180?(b=Math.cos(this.a_r)*a,d=Math.sin(this.a_r)*a):_180<this.a_r&&this.a_r<_270?(b=Math.cos(this.a_r)*a,d=Math.sin(this.a_r)*a):this.a_r==_180||0===this.a_r||this.a_r==_360?(b=this.a_r==_180?-a:a,d=0):this.a_r==_90||this.a_r==_270?(d=this.a_r>_90?-a:a,b=0):(b=Math.cos(this.a_r)*a,d=Math.sin(this.a_r)*a);vector.set(b,d);vector.addV(this.pos);for(d=cast_range.start.y;d<cast_range.end.y;d++)for(b=cast_range.start.x;b<cast_range.end.x;b++)if(map[d][b]&&
checkCollision(new Vector(b*BOX_D,d*BOX_D),vector)||map[d][++b]&&checkCollision(new Vector(b*BOX_D,d*BOX_D),vector)||map[d][++b]&&checkCollision(new Vector(b*BOX_D,d*BOX_D),vector)||map[d][++b]&&checkCollision(new Vector(b*BOX_D,d*BOX_D),vector)||map[d][++b]&&checkCollision(new Vector(b*BOX_D,d*BOX_D),vector))return this.far=a,this.end.copy(vector),this.collision=!0;return!1};Ray.prototype.set=function(a,b,d){this.pos.copy(a);this.a_r=b;this.far=d;this.end=this.calcEnd();this.collision=!1};
var v=new Vector(0,0);Ray.prototype.calcEnd=function(){v.x=Math.cos(this.a_r)*this.far;v.y=Math.sin(this.a_r)*this.far;_90<this.a_r&&this.a_r<_180?(v.x=0<v.x?-v.x:v.x,v.y=0>v.y?-v.y:v.y):_90<this.a_r&&this.a_r<_270&&(v.x=0<v.x?-v.x:v.x,v.y=0<v.y?-v.y:v.y);v.addV(this.pos);return v};
Ray.prototype.calcEndQ=function(a){var b=new Vector(0,0);b.x=this.cos*this.far;b.y=this.sin*this.far;2==a?(b.x=0<b.x?-b.x:b.x,b.y=0>b.y?-b.y:b.y):3==a?(b.x=0<b.x?-b.x:b.x,b.y=0<b.y?-b.y:b.y):4==a&&(b.x=0>b.x?-b.x:b.x,b.y=0<b.y?-b.y:b.y);b.addV(this.pos);return b};var max_x,max_y;function checkCollision(a,b){max_x=a.x+BOX_D;max_y=a.y+BOX_D;return max_x>=b.x&&b.x>=a.x?max_y>=b.y&&b.y>=a.y:!1}var _bhalf=0.5*BOX_D;
function Rappell(a,b){a instanceof Rappell?(this.start=new Vector(a.start),this.end=new Vector(a.end),this.ray=new Ray(this.end,_180,_bhalf),this.leftside=a.leftside):(this.start=new Vector(a),this.end=new Vector(a),this.ray=new Ray(this.end,_180,_bhalf),this.leftside=a.x<b.x,this.end.y+=BOX_D)}
Rappell.prototype.update=function(a){this.end.y-a.y<_bhalf&&(this.end.copy(a),this.ray.set(this.end,_90,_bhalf),this.ray.cast()?(this.end.y+=this.ray.far,player.rappelling=!1,inRopes(player.rope)||player.ropes.push(new Rappell(player.rope))):this.end.y+=_bhalf)};Rappell.prototype.onRope=function(a){for(var b=new Vector(this.start);b.y<=this.end.y;){if(5>b.distanceTo(a))return b;b.y++}return!1};Rappell.prototype.equals=function(a){return this.start==a.start&&this.end==a.end};
Rappell.prototype.draw=function(){ctx.strokeStyle=player.color;ctx.moveTo(this.start.x,this.start.y);ctx.lineTo(this.end.x,this.end.y);ctx.stroke()};
Rappell.prototype.hookUp=function(){this.ray.set(this.start,_270,0.9*BOX_D);if(this.ray.cast())return!1;this.ray.set(this.start,_90,0.9*BOX_D);if(this.ray.cast())return!1;if(this.leftside){this.ray.set(this.start,_180,BOX_D);if(this.ray.cast())return!1;this.ray.set(this.start,_45,0.75*BOX_D)}else{this.ray.set(this.start,0,BOX_D);if(this.ray.cast())return!1;this.ray.set(this.start,_135,0.75*BOX_D)}return this.ray.cast()?!1:!0};
function inRopes(a){if(0===player.ropes.length)return!1;for(var b=player.ropes.length-1;0<=b;b--)if(player.ropes[b].equals(a))return!0;return!1}
var player_ray=new Ray(new Vector(0,0),0,0),temp_v=new Vector(0,0),left,right,G=4.9,bounds={left:0,top:1,right:2,bot:3,bot_left:4,bot_right:5,top_left:6,top_right:7},player={pos:new Vector(210,210),pos_real:function(){var a=new Vector(0,0);a.copy(this.pos);a.subV(offset);return a},setPos:function(a){offset.set(player.pos.x-a.x,player.pos.y-a.y)},speed:2,jumpvar:2,rad:5,r:120,color:"ffff00",angle:toRadians(225),a_offset:15,quad:function(){return getQuad(this.angle,!0)},draw:!0,rappelling:!1,rope:!1,
ropes:[],vy:0,climbing:!1,falling:!1,fallfrom:map_h,ti:void 0,camp:!1,camps:[],bound:function(a){var b=this.pos_real().x,d=this.pos_real().y;switch(a){case 0:b-=player.rad;break;case 1:d-=player.rad;break;case 2:b+=player.rad;break;case 3:d+=player.rad;break;case 4:d+=player.rad;b-=player.rad;break;case 5:d+=player.rad;b+=player.rad;break;case 6:d-=player.rad;b-=player.rad;break;case 7:d-=player.rad,b+=player.rad}return new Vector(b,d)},isFalling:function(){if(this.climbing||this.rappelling)return!1;
left=canMove(this.bound(bounds.bot_left),_90);right=canMove(this.bound(bounds.bot_right),_90);left&&right?(this.falling=!0,this.pos_real().y<this.fallfrom&&(this.fallfrom=this.pos_real().y)):!this.falling||left&&right||(this.falling=!1,this.fallfrom=map_h,this.ti=void 0,this.vy=0);return this.falling},fall:function(a){this.pos_real().y<map_h-BOX_D&&(this.ti=this.ti||a,a=(new Date).getTime()/1E3-this.ti,this.vy+=G*a/2,player_ray.set(this.bound(bounds.bot),_90,this.vy),player_ray.cast()?(this.falling=
!1,offset.y-=player_ray.far,200<=this.pos_real().y-this.fallfrom&&0<this.fallfrom&&this.death(),this.ti=void 0,this.fallfrom=this.vy=0):offset.y-=this.vy,this.draw=!0)},death:function(){player.color="black";game=!1;document.getElementById("deadToast").className="toast"},climb:function(){left=canMove(this.bound(bounds.left),_180);right=canMove(this.bound(bounds.right),0);if(this.climbing)this.climbing=!(left&&right),this.climbing||(this.offset=left?this.offset-this.rad:this.offset+this.rad);else if(left&&
right){if(canMove(this.bound(bounds.bot_left),_90)||canMove(this.bound(bounds.bot_right),_90))this.climbing=!0}else if(left||right)if(canMove(this.bound(bounds.top_left),_270)||canMove(this.bound(bounds.top_right),_270))this.climbing=!0},doClimb:function(){player_ray.set(this.bound(bounds.top),_180,10);player_ray.cast()&&(this.climbing=!0,this.setPos(new Vector(this.pos_real().x-0.5*player_ray.far,this.pos_real().y)));player_ray.set(this.bound(bounds.top),0,10);player_ray.cast()&&(this.climbing=!0,
this.setPos(new Vector(this.pos_real().x+0.5*player_ray.far,this.pos_real().y)));return this.climbing},jump:function(){player_ray.set(this.bound(bounds.top),_270,this.speed*this.jumpvar);player_ray.cast()?offset.y+=player_ray.far:offset.y+=this.speed*this.jumpvar},buildCamp:function(){player_ray.set(this.bound(bounds.bot),_90,this.rad);if(player_ray.cast()){if(vectorIn(this.camps,this.pos_real()))return!1;this.camp||(this.camp=!0);if(2<=this.camps.length){for(var a=0,b=0,d=0;d<this.camps.length;d++)this.pos_real().distanceTo(this.camps[d])>
b&&(b=this.pos_real().distanceTo(this.camps[d]),a=d);this.camps[a].copy(new Vector(this.pos_real()))}else this.camps.push(new Vector(this.pos_real()))}},respawn:function(){var a,b=this.pos_real().distanceTo(spawn_v);if(!this.camps.length)return!1;for(var d=0;d<this.camps.length;d++)this.pos_real().distanceTo(this.camps[d])<b&&(a=d,b=offset.distanceTo(this.camps[d]));temp_v.copy(this.pos);temp_v.subV(this.camps[a]);offset.copy(temp_v);return!0},rappell:function(a){switch(a){case 87:this.pos_real().distanceTo(this.rope.start)<
this.speed?(this.rappelling=!1,this.jump()):offset.y+=this.speed;break;case 65:this.rappelling=!1;offset.x+=this.speed;break;case 83:offset.y-=this.speed;break;case 68:this.rappelling=!1,offset.x-=this.speed}this.rappelling?this.rope.update(this.pos_real()):inRopes(player.rope)||this.ropes.push(new Rappell(this.rope))},startTime:0,battery:function(){(new Date).getTime();var a=parseInt(this.color,16);a--;this.color=a.toString(16)},batteryOut:function(){0>=this.a_offset||(this.a_offset-=9E-5)},move:function(){prev_offset.copy(offset);
87 in keysDown&&canMove(this.bound(1),_270,this.speed)&&(this.climbing||this.rappelling?this.rappelling?this.rappell(87):offset.y+=this.speed:this.doClimb()||this.jump());65 in keysDown&&canMove(this.bound(0),_180)&&(this.rappelling?this.rappell(65):offset.x+=this.speed);83 in keysDown&&!this.falling&&canMove(this.bound(bounds.bot),_90,this.rad)&&(this.rappelling?this.rappell(83):offset.y-=this.speed);68 in keysDown&&canMove(this.bound(2),0)&&(this.rappelling?this.rappell(68):offset.x-=this.speed);
67 in keysDown&&(this.falling||this.climbing?this.climbing=!1:this.climb());32 in keysDown&&this.buildCamp();this.climbing&&this.climb();this.draw=!0}},ray_move=new Ray(new Vector(0,0),0,0),canMove=function(a,b,d){var e=!1;ray_move.set(a,b,d||0.5*player.rad);return e=!ray_move.cast()},spawn=new Box(new Vector(0,0),0,0,0),click=!1;
cnvs.onmousedown=function(a){a.preventDefault();a=getCords(cnvs,a.clientX,a.clientY);if(a.distanceTo(player.pos)<BOX_D){spawn.pos.offset(0.5*BOX_D,0.5*BOX_D);if(player.pos_real().distanceTo(spawn.pos)<0.5*BOX_D)document.getElementById("nextLvlToast").className="toast";else if(player.rappelling||player.falling)player.rappelling&&(player.rappelling=!1,inRopes(player.rope)||player.ropes.push(new Rappell(player.rope)));else{a.subV(offset);var b=onRope(a);b?player.setPos(b):(player.rope=new Rappell(a,
player.pos_real()),player.rope.hookUp()&&(player.setPos(player.rope.end),player.rope.end.y+=_bhalf,player.rappelling=!0,player.draw=!0))}spawn.pos.offset(0.5*-BOX_D,0.5*-BOX_D)}};cnvs.onmousemove=function(a){a.preventDefault();a=getCords(cnvs,a.clientX,a.clientY);a.subV(offset);player.angle=toRadians(getAngle(player.pos_real(),a));player.draw=!0};var keysDown={},moved=!1;function keydown(a){a.preventDefault();moved=keysDown[a.keyCode]=!0}function keyup(a){delete keysDown[a.keyCode];moved=!1}
addEventListener("keydown",keydown,!1);addEventListener("keyup",keyup,!1);
var update=function(){player.isFalling()&&player.fall((new Date).getTime()/1E3);moved&&player.move();player.batteryOut()},tempv=new Vector(0,0),draw=function(){player.draw&&(draw_window.copy(player.pos_real()),draw_window.offset(-(player.r+5),-(player.r+5)),draw_x=draw_y=2*(player.r+10),draw_end.set(draw_x,draw_y),draw_end.addV(draw_window),ctx.clearRect(0,0,w,h),ctx.save(),ctx.translate(offset.x,offset.y),draw_map&&drawMap(BOX_D),drawOutLine(),spawn.draw("yellow"),player.rappelling&&player.rope.draw(),
player.ropes.length&&drawRopes(),ctx.clearRect(0,0,w,draw_window.y),ctx.clearRect(0,0,draw_window.x,h),ctx.clearRect(0,draw_end.y,w,h),ctx.clearRect(draw_end.x,0,w,h),player.camp&&drawCamps(),ctx.restore(),ctx.save(),drawCone(player.pos_real(),player.angle,player.r,player.a_offset),ctx.restore(),player.draw=!1)},ray_light=new Ray(new Vector(0,0),0,0),skip=!1,draw_outline=!1;
function drawLine(a,b,d){ray_light.set(a,b,d);ray_light.cast();a.addV(offset);ray_light.end.addV(offset);ctx.beginPath();ctx.moveTo(a.x,a.y);ctx.lineTo(ray_light.end.x,ray_light.end.y);ctx.closePath();ctx.stroke();0>=player.a_offset||!ray_light.collision||!draw_outline||(ray_light.end.subV(offset),ray_light.end.x=Math.floor(ray_light.end.x),ray_light.end.y=Math.floor(ray_light.end.y),vectorIn(outline,ray_light.end)||outline.push(new Vector(ray_light.end.x,ray_light.end.y)))}
function drawCone(a,b,d,e){b=toDegrees(b);ctx.strokeStyle=player.color;for(var f=b-e;f<=b+e;f++)drawLine(new Vector(a),toRadians(f),d)}function drawOutLine(){if(0===outline.length)return!1;ctx.fillStyle="gray";for(var a=outline.length-1;0<=a;a--)outline[a].x<draw_window.x||outline[a].y<draw_window.y||draw_end.x<outline[a].x||draw_end.y<outline[a].y||ctx.fillRect(outline[a].x,outline[a].y,1,1)}
function drawCamp(a){ctx.fillStyle="yellow";ctx.beginPath();ctx.arc(a.x,a.y,player.rad,0,2*Math.PI,!1);ctx.stroke();ctx.fill();ctx.closePath()}function drawCamps(){for(var a=player.camps.length-1;0<=a;a--)drawCamp(player.camps[a])}function drawRopes(){for(var a=player.ropes.length-1;0<=a;a--)(200>player.ropes[a].start.distanceTo(player.pos_real())||200>player.ropes[a].end.distanceTo(player.pos_real()))&&player.ropes[a].draw()}
function onRope(a){for(var b,d=player.ropes.length-1;0<=d;d--)if(b=player.ropes[d].onRope(a))return player.rope=player.ropes[d],player.rappelling=!0,b;return!1}function getMapRange(a,b){var d=new Vector(0,0),e=new Vector(0,0),f,g;f=Math.floor((a.x-b)/BOX_D);g=Math.floor((a.y-b)/BOX_D);d.x=0>f?0:f;d.y=0>g?0:g;f=Math.round((a.x+b)/BOX_D);g=Math.round((a.y+b)/BOX_D);e.x=f>size_x?size_x:f;e.y=g>size_y?size_y:g;return{start:d,end:e}}
function getSpawnVector(){for(r=1;r<size_y;r++)for(c=1;c<size_x;c++)if(map[r][c]===TILE_FLOOR&&map[r+1][c]===TILE_WALL)return spawn.set(c*BOX_D,r*BOX_D,BOX_D,0),spawn_v.set(c,r),new Vector(spawn.pos.x+0.5*BOX_D,spawn.pos.y+0.5*BOX_D)}var background_audio=new Audio("static/Background.mp3");background_audio.loop=!0;background_audio.volume=1;background_audio.load();var game=!1,sound=!0;
function init(){do ctx.clearRect(0,0,w,h),createMap(BOX_D),outline.length=0,player.pos.copy(getSpawnVector()),player.color="yellow";while(!checkMap(spawn_v));offset.set(0.5*w,0.5*h);offset.subV(player.pos);player.pos.addV(offset);player.camps=[];player.ropes.length=0;player.startTime=(new Date).getTime()/1E3;player.color="ffff00";player.a_offset=15;background_audio.play();document.getElementById("introToast").className="invis";game=!0;setInterval(main,1)}
var main=function(){var a=new Vector(0,0);a.copy(player.pos);a.subV(offset);if(!game)return!1;cast_range=getMapRange(a,player.r);update();draw()};